spring:
  datasource:
    url: jdbc:mysql://db:3306/hippocrates?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5 #连接池初始化大小
    min-idle: 10 #最小空闲连接数
    max-active: 20 #最大连接数
server:
  port: 8081
  servlet:
    context-path: /hipp
